# @package _global_

rewards:
  set_reward: KickPrimitiveTrackingAligned
  set_reward_date: 20260424
  only_positive_rewards: False
  reward_scales:
      teleop_body_position_extend: 1.0
      teleop_vr_3point: 1.0
      teleop_body_position_feet: 3.0
      teleop_body_rotation_extend: 0.5
      teleop_body_ang_velocity_extend: 0.5
      teleop_body_velocity_extend: 0.8
      teleop_joint_position: 1.5
      tracking_joint_position_right_ankle: 0.5
      teleop_joint_velocity: 1.5   # 突然觉得这个很重要，决定是踢还是把腿摆在哪里，之后从1.5加大试试
      penalty_torques: -0.000001
      penalty_action_rate: -0.05
      limits_dof_pos: -10.0
      limits_dof_vel: -5.0
      limits_torque: -0.1
      termination: -130.0

  teleop_body_pos_lowerbody_weight: 0.5
  teleop_body_pos_upperbody_weight: 1.0

  reward_tracking_sigma:
    teleop_upper_body_pos: 0.03
    teleop_lower_body_pos: 0.1
    teleop_vr_3point_pos: 0.03
    teleop_feet_pos: 0.03

    teleop_body_rot: 1.0
    teleop_body_vel: 1.0
    teleop_body_ang_vel: 1.0
    teleop_joint_pos: 1.0
    teleop_joint_vel: 1.0

  tracking_right_ankle_dof_names: [
    "right_ankle_pitch_joint",
    "right_ankle_roll_joint"
  ]
  tracking_right_ankle_sigma: 0.08

  reward_limit:
    soft_dof_pos_limit: 0.95
    soft_dof_vel_limit: 0.95
    soft_torque_limit: 0.95

    reward_limits_curriculum:
      soft_dof_pos_curriculum: False
      soft_dof_pos_initial_limit: 1.25
      soft_dof_pos_max_limit: 1.25
      soft_dof_pos_min_limit: 0.95
      soft_dof_pos_curriculum_degree: 0.0000003
      soft_dof_pos_curriculum_level_down_threshold: 40
      soft_dof_pos_curriculum_level_up_threshold: 42

      soft_dof_vel_curriculum: False
      soft_dof_vel_initial_limit: 1.25
      soft_dof_vel_max_limit: 1.25
      soft_dof_vel_min_limit: 0.95
      soft_dof_vel_curriculum_degree: 0.0000003
      soft_dof_vel_curriculum_level_down_threshold: 40
      soft_dof_vel_curriculum_level_up_threshold: 42

      soft_torque_curriculum: False
      soft_torque_initial_limit: 1.25
      soft_torque_max_limit: 1.25
      soft_torque_min_limit: 0.85
      soft_torque_curriculum_degree: 0.0000003
      soft_torque_curriculum_level_down_threshold: 40
      soft_torque_curriculum_level_up_threshold: 42

  reward_penalty_curriculum: False
  reward_initial_penalty_scale: 0.1
  reward_min_penalty_scale: 0.0
  reward_max_penalty_scale: 1.0
  reward_penalty_level_down_threshold: 50
  reward_penalty_level_up_threshold: 100
  reward_penalty_degree: 0.00001
  num_compute_average_epl: 10000

  reward_penalty_reward_names: [
    "penalty_torques",
    "penalty_dof_acc",
    "penalty_dof_vel",
    "penalty_action_rate",
    "limits_dof_pos",
    "limits_dof_vel",
    "limits_torque"
  ]
